### ISSUE TITLE
French translation for case insensitive does not sound natural

### ISSUE THREAD

**Issue by brunolewin** [mspnp/architecture-center.fr-fr#3]
The French translation of "case insensitive" ("non-respect de la casse" = lit. "no respect for case") in "case" column does not feel right, esp. in this context.

Something like "insensible à la casse" (as used in e.g. https://docs.microsoft.com/fr-fr/azure/data-factory/naming-rules) would feel much more natural to me here.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 0e540bb6-9f72-0529-28ea-ae82bc869835
* Version Independent ID: 24e71392-985b-59fb-1552-46395b169612
* Content: [Conventions d’affectation de noms pour les ressources Azure - Best practices for cloud applications](https://docs.microsoft.com/fr-fr/azure/architecture/best-practices/naming-conventions)
* Content Source: [docs/best-practices/naming-conventions.md](https://github.com/mspnp/architecture-center.fr-fr/blob/live/docs/best-practices/naming-conventions.md)
* Service: **architecture-center**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by LisandroSu** [comment]
Hello, @brunolewin 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @brunolewin 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/architecture/best-practices/naming-conventions

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
